version: '3'
services:
  gekko:
    image: gekko:latest
    build: ./
    volumes:
      - /root/history:/usr/src/app/history
      - ./config.js:/usr/src/app/config.js
    links:
      - redis
    environment:
     - HOST
     - PORT
    ports: # you can comment this out when using the nginx frontend
      - "${PORT}"
    expose:
      - "5000"
## optionally set nginx vars if you wish to frontend it with nginx
#   environment:
#    - VIRTUAL_HOST=gekko
#    - PORT=3000
#    - DOMAIN=gekko
  redis:
    image: redis:latest
    volumes:
      - ./volumes/redis:/data
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gekko
    ports:
      - "4000:4000"
